### ISSUE TITLE
Create BED files for upload and viewing in UCSC browser

### ISSUE THREAD

**Issue by thefferon** [ncbi/dbvar#10]
It would be really helpful if you would provide the non-redundant variants in BED format, so users could upload them to the UCSC genome browser, or similar browsers.

VCF could also be really useful, especially in the context of annotations... Then these data could easily be incorporated into bioinformatics workflows...

**Comment by lonphan** [comment]
BED  and BEDPE are now available on FTP.
https://ftp.ncbi.nlm.nih.gov/pub/dbVar/sandbox/sv_datasets/nonredundant/#github
